#!/usr/bin/env python3
"""Behavioral acceptance checks for the canonical plugin generator."""

from __future__ import annotations

import datetime
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable


ROOT = Path(__file__).resolve().parent.parent
GENERATOR = ROOT / "tools" / "generate-plugins.py"
PLUGINS_ROOT = ROOT / "plugins"
PYTHON = "python3"

PLUGINS = {
    "adt-pair": {"pair-planner", "pair-implementer", "design-grill"},
    "adt-orchestrator": {
        "pair-planner",
        "pair-implementer",
        "design-grill",
        "orchestrator-planner",
        "orchestrator-reviewer",
        "sprint-doc-setup",
    },
    "adt-master": {
        "pair-planner",
        "pair-implementer",
        "design-grill",
        "orchestrator-planner",
        "orchestrator-reviewer",
        "sprint-doc-setup",
        "domain-planner",
        "domain-reviewer",
        "master-planner",
        "master-reviewer",
    },
}
REVIEW_ASSETS = {
    "review-panels.md",
    "reviewer-spawn-prompts.md",
    "design-request-template.md",
}
REVIEW_SKILLS = {"pair-planner", "orchestrator-planner"}
MASTER_SKILLS = {"domain-planner", "domain-reviewer", "master-planner", "master-reviewer"}
VOCABULARY = (
    ("Master Planner", "t-x.master-planner"),
    ("Master Reviewer", "t-x.master-reviewer"),
    ("Domain Planner", "t-x.domain-planner"),
    ("Domain Reviewer", "t-x.domain-reviewer"),
    ("Pair Planner", "t-x.pair-planner"),
    ("Pair Implementer", "t-x.pair-implementer"),
    ("Planner", "t-x.planner"),
)


def expect(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def output(result: subprocess.CompletedProcess[str]) -> str:
    return (result.stdout + result.stderr).strip()


def run_generator(root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [PYTHON, str(root / "tools" / "generate-plugins.py"), *arguments],
        cwd=root,
        text=True,
        capture_output=True,
    )


def expect_success(result: subprocess.CompletedProcess[str], context: str) -> None:
    expect(result.returncode == 0, f"{context} exited {result.returncode}: {output(result)}")


def expect_drift(result: subprocess.CompletedProcess[str], path: str) -> None:
    expect(result.returncode == 1, f"drift for {path} exited {result.returncode}: {output(result)}")
    expect(f"different: {path}" in output(result), f"drift for {path} was not reported: {output(result)}")


def file_map(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def copy_generator_inputs(destination: Path) -> Path:
    destination.mkdir(exist_ok=True)
    fixture = destination / "repo"
    fixture.mkdir()
    for name in ("skills", "shared", "tools", "vendor", "LICENSE", "LICENSES"):
        source = ROOT / name
        target = fixture / name
        if source.is_dir():
            shutil.copytree(source, target, ignore=shutil.ignore_patterns("__pycache__"))
        else:
            shutil.copy2(source, target)
    return fixture


def copy_repository_fixture(destination: Path) -> Path:
    fixture = copy_generator_inputs(destination)
    shutil.copytree(PLUGINS_ROOT, fixture / "plugins")
    return fixture


def check_determinism() -> None:
    with tempfile.TemporaryDirectory(prefix="check-generate-plugins-") as temporary:
        temp_root = Path(temporary)
        first = copy_generator_inputs(temp_root / "first")
        second = copy_generator_inputs(temp_root / "second")
        expect_success(run_generator(first), "first generation")
        expect_success(run_generator(second), "second generation")
        expect(file_map(first / "plugins") == file_map(second / "plugins"), "two isolated generations differ")


def check_clean() -> None:
    expect_success(run_generator(ROOT, "--check"), "clean --check")


def check_manifest_mutation() -> None:
    with tempfile.TemporaryDirectory(prefix="check-generate-plugins-") as temporary:
        fixture = copy_repository_fixture(Path(temporary))
        manifest = fixture / "plugins" / "PROVENANCE.json"
        manifest.write_bytes(manifest.read_bytes() + b" ")
        expect_drift(run_generator(fixture, "--check"), "PROVENANCE.json")
        expect_success(run_generator(fixture), "manifest mutation regeneration")
        expect_success(run_generator(fixture, "--check"), "manifest mutation regenerated --check")


def check_banner_mutation() -> None:
    with tempfile.TemporaryDirectory(prefix="check-generate-plugins-") as temporary:
        fixture = copy_repository_fixture(Path(temporary))
        relative = "adt-pair/skills/pair-planner/SKILL.md"
        generated = fixture / "plugins" / relative
        text = generated.read_text(encoding="utf-8")
        expect(text.startswith("<!-- GENERATED by tools/generate-plugins.py"), "target lacks generated banner")
        generated.write_text(text.replace("kit v2.9.0", "kit v0.0.0", 1), encoding="utf-8")
        expect_drift(run_generator(fixture, "--check"), relative)


def check_body_mutation() -> None:
    with tempfile.TemporaryDirectory(prefix="check-generate-plugins-") as temporary:
        fixture = copy_repository_fixture(Path(temporary))
        relative = "adt-pair/skills/pair-planner/SKILL.md"
        generated = fixture / "plugins" / relative
        text = generated.read_text(encoding="utf-8")
        expect("name: pair-planner" in text, "target lacks expected generated skill body")
        generated.write_text(text.replace("name: pair-planner", "name: altered-planner", 1), encoding="utf-8")
        expect_drift(run_generator(fixture, "--check"), relative)


def check_strict_json() -> None:
    json_files = sorted(PLUGINS_ROOT.rglob("*.json"))
    expect(json_files, "no generated JSON files found")
    for path in json_files:
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise AssertionError(f"invalid JSON in {path.relative_to(ROOT)}: {error}") from error


def check_inventory() -> None:
    actual_plugins = {path.name for path in PLUGINS_ROOT.iterdir() if path.is_dir()}
    expect(actual_plugins == set(PLUGINS), f"plugin inventory differs: expected {set(PLUGINS)}, got {actual_plugins}")
    for plugin, expected_skills in PLUGINS.items():
        actual_skills = {path.name for path in (PLUGINS_ROOT / plugin / "skills").iterdir() if path.is_dir()}
        expect(
            actual_skills == expected_skills,
            f"{plugin} skill inventory differs: missing {expected_skills - actual_skills}, extra {actual_skills - expected_skills}",
        )


def check_adjacency() -> None:
    for plugin, skills in PLUGINS.items():
        plugin_root = PLUGINS_ROOT / plugin
        for skill in skills:
            skill_root = plugin_root / "skills" / skill
            expect((skill_root / "protocol.md").is_file(), f"{plugin}/{skill} lacks protocol.md")
            if skill in REVIEW_SKILLS:
                for asset in REVIEW_ASSETS:
                    expect((skill_root / asset).is_file(), f"{plugin}/{skill} lacks {asset}")
            if skill in MASTER_SKILLS:
                expect(plugin == "adt-master", f"{plugin}/{skill} is a master-only skill outside adt-master")
                expect((skill_root / "master-tier-boundary.md").is_file(), f"{plugin}/{skill} lacks master-tier-boundary.md")
        for required in (
            "tools/relay-lint.py",
            "vendor/mattpocock/grill-me/SKILL.md",
            "LICENSE",
        ):
            expect((plugin_root / required).is_file(), f"{plugin} lacks file {required}")
        for required in ("tools/relay-lint-fixtures", "tools/adapters", "LICENSES"):
            expect((plugin_root / required).is_dir(), f"{plugin} lacks directory {required}")


def install_tier(plugin: str, scratch_base: Path) -> Path:
    scratch = scratch_base / plugin
    plugin_root = PLUGINS_ROOT / plugin
    shutil.copytree(plugin_root / "skills", scratch / "skills")
    shutil.copytree(plugin_root / "tools", scratch / "tools")
    return scratch


def run_linter(linter: Path, relay: Path, empty_cwd: Path, *, no_freshness: bool = False) -> subprocess.CompletedProcess[str]:
    arguments = [PYTHON, str(linter), str(relay)]
    if no_freshness:
        arguments.append("--no-freshness")
    return subprocess.run(arguments, cwd=empty_cwd, text=True, capture_output=True)


def check_cold_install(scratch_base: Path) -> dict[str, Path]:
    installations: dict[str, Path] = {}
    for plugin, skills in PLUGINS.items():
        scratch = install_tier(plugin, scratch_base)
        installations[plugin] = scratch
        for skill in skills:
            skill_root = scratch / "skills" / skill
            expect((skill_root / "protocol.md").is_file(), f"{plugin} cold install lacks {skill}/protocol.md")
            if skill in REVIEW_SKILLS:
                for asset in REVIEW_ASSETS:
                    expect((skill_root / asset).is_file(), f"{plugin} cold install lacks {skill}/{asset}")
            if skill in MASTER_SKILLS:
                expect((skill_root / "master-tier-boundary.md").is_file(), f"{plugin} cold install lacks {skill}/master-tier-boundary.md")
        linter = scratch / "tools" / "relay-lint.py"
        fixture = scratch / "tools" / "relay-lint-fixtures" / "claude" / "A1-valid-audit.md"
        expect(linter.is_file(), f"{plugin} cold install lacks tools/relay-lint.py")
        expect(fixture.is_file(), f"{plugin} cold install lacks claude/A1-valid-audit.md")
        empty_cwd = scratch_base / f"empty-cwd-{plugin}"
        empty_cwd.mkdir()
        expect_success(run_linter(linter, fixture, empty_cwd, no_freshness=True), f"{plugin} cold-install linter")
    return installations


def relay_text(role: str, address: str) -> str:
    return "\n".join(
        (
            f"ROLE: {role}",
            "PHASE: AUDIT",
            "AUTHORITY: read-only",
            "DISPATCH_ID: task-7-vocabulary",
            "CEREMONY_TIER: small",
            "EVIDENCE_TARGET: E1",
            "HUMAN_GATE_REQUIRED: no",
            f"FROM: {address}",
            "TO: operator",
            "",
            "FINAL_GIT_STATUS_SHORT: none — clean tree",
            "",
        )
    )


def check_protocol_linter_coherence(installations: dict[str, Path], scratch_base: Path) -> None:
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    for plugin, scratch in installations.items():
        for skill in PLUGINS[plugin]:
            protocol = (scratch / "skills" / skill / "protocol.md").read_text(encoding="utf-8")
            for role, address in VOCABULARY:
                suffix = address.rsplit(".", 1)[1]
                expect(role in protocol, f"{plugin} {skill} protocol lacks ROLE vocabulary {role}")
                expect(f"`{suffix}`" in protocol, f"{plugin} {skill} protocol lacks address vocabulary {suffix}")
        relay_root = scratch / "acceptance-relays"
        relay_root.mkdir()
        empty_cwd = scratch_base / f"coherence-empty-cwd-{plugin}"
        empty_cwd.mkdir()
        linter = scratch / "tools" / "relay-lint.py"
        for role, address in VOCABULARY:
            filename_role = role.lower().replace(" ", "-")
            relay = relay_root / f"AUDIT-{filename_role}-{stamp}.md"
            relay.write_text(relay_text(role, address), encoding="utf-8")
            expect_success(run_linter(linter, relay, empty_cwd), f"{plugin} vocabulary {role}/{address}")


def check_no_json_banner() -> None:
    for path in sorted(PLUGINS_ROOT.rglob("*.json")):
        first = path.read_bytes()[:1]
        expect(first not in {b"<", b"#"}, f"comment banner found in {path.relative_to(ROOT)}")


def run_check(name: str, check: Callable[[], object]) -> tuple[bool, object | None]:
    try:
        result = check()
    except Exception as error:
        print(f"FAIL {name}: {error}")
        return False, None
    print(f"PASS {name}")
    return True, result


def main() -> int:
    if not GENERATOR.is_file():
        print("FAIL generator present: generate-plugins.py not found")
        return 1

    failures = 0
    for name, check in (
        ("determinism", check_determinism),
        ("clean --check", check_clean),
        ("manifest mutation", check_manifest_mutation),
        ("banner mutation", check_banner_mutation),
        ("body mutation", check_body_mutation),
        ("strict JSON", check_strict_json),
        ("inventory", check_inventory),
        ("adjacency", check_adjacency),
    ):
        passed, _ = run_check(name, check)
        if not passed:
            failures += 1

    with tempfile.TemporaryDirectory(prefix="check-generate-plugins-cold-install-") as temporary:
        scratch_base = Path(temporary)
        cold_install_passed, installations = run_check("cold install", lambda: check_cold_install(scratch_base))
        no_banner_passed, _ = run_check("no banner in comment-free formats", check_no_json_banner)
        if not no_banner_passed:
            failures += 1
        if not cold_install_passed:
            failures += 1
            print("FAIL protocol/linter coherence: cold install did not produce scratch installations")
            failures += 1
        else:
            coherence_passed, _ = run_check(
                "protocol/linter coherence",
                lambda: check_protocol_linter_coherence(installations, scratch_base),
            )
            if not coherence_passed:
                failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
