#!/usr/bin/env python3
"""Behavioral checks for the canonical plugin generator."""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GENERATOR = ROOT / "tools" / "generate-plugins.py"
PLUGINS = {
    "adt-pair": ("pair-planner", "pair-implementer", "design-grill"),
    "adt-orchestrator": (
        "pair-planner",
        "pair-implementer",
        "design-grill",
        "orchestrator-planner",
        "orchestrator-reviewer",
        "sprint-doc-setup",
    ),
    "adt-master": (
        "pair-planner",
        "pair-implementer",
        "design-grill",
        "orchestrator-planner",
        "orchestrator-reviewer",
        "sprint-doc-setup",
        "domain-planner",
        "domain-reviewer",
        "master-planner",
        "master-reviewer",
    ),
}


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def expect(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def main() -> int:
    if not GENERATOR.is_file():
        fail("generate-plugins.py not found")

    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    expect(result.returncode == 0, result.stdout + result.stderr)

    plugins_root = ROOT / "plugins"
    expected_root_entries = set(PLUGINS) | {"PROVENANCE.json"}
    expect(
        {path.name for path in plugins_root.iterdir()} == expected_root_entries,
        "plugins/ root inventory differs from the three generated bundles and manifest",
    )

    for plugin, skills in PLUGINS.items():
        plugin_root = plugins_root / plugin
        manifest_path = plugin_root / ".claude-plugin" / "plugin.json"
        manifest_text = manifest_path.read_text(encoding="utf-8")
        expect(not manifest_text.startswith("<!-- GENERATED"), f"{manifest_path} has a banner")
        manifest = json.loads(manifest_text)
        expect(manifest["name"] == plugin, f"{manifest_path} has the wrong name")
        expect(manifest["version"] == "2.9.0", f"{manifest_path} has the wrong version")
        expect(
            {path.name for path in (plugin_root / "skills").iterdir()} == set(skills),
            f"{plugin} skill inventory is wrong",
        )
        for skill in skills:
            skill_file = plugin_root / "skills" / skill / "SKILL.md"
            expect(skill_file.is_file(), f"{skill_file} is missing")
            expect(
                skill_file.read_text(encoding="utf-8").startswith("<!-- GENERATED by tools/generate-plugins.py from skills/"),
                f"{skill_file} lacks its markdown provenance banner",
            )

    protocol = plugins_root / "adt-pair" / "skills" / "pair-planner" / "protocol.md"
    expect(protocol.is_file(), f"{protocol} is missing")
    expect(
        protocol.read_text(encoding="utf-8").startswith(
            "<!-- GENERATED by tools/generate-plugins.py from shared/protocol.md — kit v2.9.0. Do not edit; edit the canonical source. -->\n\n"
        ),
        f"{protocol} has the wrong banner",
    )

    provenance_path = plugins_root / "PROVENANCE.json"
    provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
    paths = [entry["path"] for entry in provenance]
    expect(paths == sorted(paths), "PROVENANCE.json paths are not sorted")
    expect("PROVENANCE.json" not in paths, "PROVENANCE.json hashes itself")
    generated_paths = sorted(
        path.relative_to(plugins_root).as_posix()
        for path in plugins_root.rglob("*")
        if path.is_file() and path != provenance_path
    )
    expect(paths == generated_paths, "PROVENANCE.json does not inventory every generated file")
    for entry in provenance:
        generated = plugins_root / entry["path"]
        expect(entry["kit_version"] == "2.9.0", f"{entry['path']} has the wrong kit version")
        expect(
            entry["sha256"] == hashlib.sha256(generated.read_bytes()).hexdigest(),
            f"{entry['path']} has the wrong sha256",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
