#!/usr/bin/env python3
"""Generate byte-exact Claude Code plugin bundles from canonical sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import stat
import sys
import tempfile
from pathlib import Path
from typing import Iterable


KIT_VERSION = "2.9.0"
MANIFEST_PATH = "PROVENANCE.json"
ROOT = Path(__file__).resolve().parent.parent
OUTPUT_ROOT = ROOT / "plugins"

PLUGINS = {
    "adt-pair": {
        "description": "Pair-tier planning and implementation skills for governed software work.",
        "skills": ("pair-planner", "pair-implementer", "design-grill"),
        "keywords": ("agents", "pair", "planning", "review", "relays"),
    },
    "adt-orchestrator": {
        "description": "Nested pair and orchestration skills for governed software work.",
        "skills": (
            "pair-planner",
            "pair-implementer",
            "design-grill",
            "orchestrator-planner",
            "orchestrator-reviewer",
            "sprint-doc-setup",
        ),
        "keywords": ("agents", "orchestration", "planning", "review", "relays"),
    },
    "adt-master": {
        "description": "Nested pair, orchestration, domain, and master planning skills.",
        "skills": (
            "pair-planner",
            "pair-implementer",
            "design-grill",
            "orchestrator-planner",
            "orchestrator-reviewer",
            "sprint-doc-setup",
            "domain-planner",
            "domain-reviewer",
            "master-planner",
            "master-reviewer",
        ),
        "keywords": ("agents", "domain", "master", "orchestration", "relays"),
    },
}

SHARED_MAP = {
    "protocol.md": tuple(skill for plugin in PLUGINS.values() for skill in plugin["skills"]),
    "review-panels.md": ("pair-planner", "orchestrator-planner"),
    "reviewer-spawn-prompts.md": ("pair-planner", "orchestrator-planner"),
    "design-request-template.md": ("pair-planner", "orchestrator-planner"),
    "master-tier-boundary.md": (
        "domain-planner",
        "domain-reviewer",
        "master-planner",
        "master-reviewer",
    ),
}

TOOLS_SET = (
    "relay-lint.py",
    "check-relay-lint-fixtures.py",
    "check-timestamp-drift.py",
    "relay-lint-fixtures",
    "adapters",
)


def sorted_files(path: Path) -> Iterable[Path]:
    return sorted((item for item in path.rglob("*") if item.is_file()), key=lambda item: item.as_posix())


def source_relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def banner(source: str, suffix: str, data: bytes) -> bytes:
    message = (
        f"GENERATED by tools/generate-plugins.py from {source} — kit v{KIT_VERSION}. "
        "Do not edit; edit the canonical source."
    ).encode("utf-8")
    if suffix == ".md":
        return b"<!-- " + message + b" -->\n\n" + data
    if suffix in {".py", ".sh"}:
        prefix = b"# " + message + b"\n\n"
        if data.startswith(b"#!"):
            shebang, newline, rest = data.partition(b"\n")
            return shebang + newline + prefix + rest
        return prefix + data
    return data


def copy_file(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    rendered = banner(source_relative(source), source.suffix, source.read_bytes())
    destination.write_bytes(rendered)
    destination.chmod(stat.S_IMODE(source.stat().st_mode))


def copy_tree(source: Path, destination: Path) -> None:
    for file_path in sorted_files(source):
        copy_file(file_path, destination / file_path.relative_to(source))


def write_plugin_manifest(plugin: str, data: dict[str, object], destination: Path) -> None:
    payload = {
        "author": "Jack Li",
        "description": data["description"],
        "keywords": list(data["keywords"]),
        "license": "Apache-2.0",
        "name": plugin,
        "version": KIT_VERSION,
    }
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_provenance(output: Path) -> None:
    entries = []
    for generated in sorted_files(output):
        relative_path = generated.relative_to(output).as_posix()
        if relative_path == MANIFEST_PATH:
            continue
        entries.append(
            {
                "path": relative_path,
                "source": "tools/generate-plugins.py"
                if relative_path.endswith("/.claude-plugin/plugin.json")
                else generated_source(output, generated),
                "sha256": hashlib.sha256(generated.read_bytes()).hexdigest(),
                "kit_version": KIT_VERSION,
            }
        )
    (output / MANIFEST_PATH).write_text(
        json.dumps(sorted(entries, key=lambda entry: entry["path"]), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def generated_source(output: Path, generated: Path) -> str:
    """Read the canonical source recorded while populating the output tree."""
    return GENERATED_SOURCES[generated.relative_to(output).as_posix()]


GENERATED_SOURCES: dict[str, str] = {}


def record_copy(source: Path, destination: Path, output: Path) -> None:
    copy_file(source, destination)
    GENERATED_SOURCES[destination.relative_to(output).as_posix()] = source_relative(source)


def record_tree(source: Path, destination: Path, output: Path) -> None:
    for file_path in sorted_files(source):
        record_copy(file_path, destination / file_path.relative_to(source), output)


def generate_tree(output: Path) -> None:
    GENERATED_SOURCES.clear()
    for plugin, data in sorted(PLUGINS.items()):
        plugin_root = output / plugin
        skills = tuple(data["skills"])
        for skill in sorted(skills):
            record_tree(ROOT / "skills" / skill, plugin_root / "skills" / skill, output)
        for shared_asset, receiving_skills in sorted(SHARED_MAP.items()):
            for skill in sorted(set(skills) & set(receiving_skills)):
                record_copy(
                    ROOT / "shared" / shared_asset,
                    plugin_root / "skills" / skill / shared_asset,
                    output,
                )
        for tool in sorted(TOOLS_SET):
            source = ROOT / "tools" / tool
            destination = plugin_root / "tools" / tool
            if source.is_dir():
                record_tree(source, destination, output)
            else:
                record_copy(source, destination, output)
        record_tree(ROOT / "vendor", plugin_root / "vendor", output)
        record_copy(ROOT / "LICENSE", plugin_root / "LICENSE", output)
        record_tree(ROOT / "LICENSES", plugin_root / "LICENSES", output)
        manifest = plugin_root / ".claude-plugin" / "plugin.json"
        write_plugin_manifest(plugin, data, manifest)
    write_provenance(output)


def file_map(root: Path) -> dict[str, bytes]:
    if not root.exists():
        return {}
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted_files(root)
    }


def check_tree(expected: Path, actual: Path) -> int:
    expected_files = file_map(expected)
    actual_files = file_map(actual)
    paths = sorted(set(expected_files) | set(actual_files))
    differences = []
    for path in paths:
        if path not in actual_files:
            differences.append(f"missing: {path}")
        elif path not in expected_files:
            differences.append(f"extra: {path}")
        elif expected_files[path] != actual_files[path]:
            differences.append(f"different: {path}")
    if differences:
        print("plugin generation drift:", file=sys.stderr)
        print("\n".join(differences), file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when plugins/ has generation drift")
    arguments = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="agentic-dev-team-skills-plugins-") as temporary:
        staging = Path(temporary) / "plugins"
        staging.mkdir()
        generate_tree(staging)
        if arguments.check:
            return check_tree(staging, OUTPUT_ROOT)
        if OUTPUT_ROOT.exists():
            shutil.rmtree(OUTPUT_ROOT)
        shutil.move(str(staging), str(OUTPUT_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
